banks = [
    "Ngân hàng An Bình",
    "Ngân hàng Á Châu",
    "Ngân hàng NN & PTNT VN",
    "Ngân hàng ANZ Việt Nam",
    "BANGKOK  BANK",
    "Công ty cổ phần chuyển mạch tài chính quốc gia Việt Nam",
    "Ngân hàng TMCP Bảo Việt",
    "BANK OF CHINA",
    "NH ĐT&PT Campuchia CN HCM",
    "NH ĐT&PT Campuchia CN Hà Nội",
    "Ngân hàng Đầu tư và Phát triển Việt Nam",
    "BNP Paribas Bank HCM",
    "Ngan hang BNP Paribas CN Ha Noi",
    "Bank of Communications",
    "Ngân hàng BPCEIOM CN  TP Hồ Chí Minh",
    "BANK OF TOKYO - MITSUBISHI UFJ - TP HCM",
    "BANK OF TOKYO - MITSUBISHI UFJ - HN",
    "Credit Agricole Corporate and Investment Bank",
    "Commonwealth Bank of Australia",
    "China Construction Bank Corporation",
    "The Chase Manhattan Bank",
    "Ngân hàng TNHH MTV CIMB Việt Nam",
    "Citi Bank TP HCM",
    "Citi Bank Ha Noi",
    "Ngân hàng Hợp tác Việt Nam",
    "Ngân hàng CTBC CN TP Hồ Chí Minh",
    "Ngân hàng Cathay",
    "DEUTSCHE BANK",
    "DBS Bank Ltd",
    "Ngân hàng Đông Á",
    "Ngân hàng Xuất nhập khẩu Việt Nam",
    "First Commercial Bank",
    "First Commercial Bank Ha Noi",
    "Ngân hàng Dầu khí Toàn cầu",
    "Ngân hàng Phát triển TP HCM",
    "Ngân hàng Hong Leong Viet Nam",
    "Hua Nan Commercial Bank",
    "NH TNHH Một Thành Viên HSBC Việt Nam",
    "Ngân hàng The Hongkong và Thượng Hải",
    "Industrial Bank of Korea",
    "ICB of China CN Ha Noi",
    "Indovina Bank",
    "Kho Bạc Nhà Nước",
    "Korea Exchange Bank",
    "Ngân hàng Kiên Long",
    "Ngân hàng Kookmin",
    "Ngan hàng TMCP Bưu điện Liên Việt",
    "Ngân hàng Hàng Hải Việt Nam",
    "Malayan Banking Berhad",
    "Ngân hàng Quân Đội",
    "Malayan Banking Berhad",
    "Mizuho Corporate Bank - TP HCM",
    "Mega ICBC Bank",
    "Mizuho Corporate Bank",
    "Ngân hàng Nam Á",
    "Ngân hàng Bắc Á",
    "Ngân hàng Quoc Dan",
    "Oversea - Chinese Bank",
    "Ngân hàng Đại Dương",
    "Ngân hàng Phương Đông",
    "Ngân hàng Xăng dầu Petrolimex",
    "NH TMCP Đại Chúng Viet Nam",
    "Quỹ tín dụng cơ sở",
    "Ngân hàng Sài Gòn Thương Tín",
    "Ngân hàng Sài Gòn Công Thương",
    "Ngân Hàng Nhà Nước",
    "Ngân hàng TMCP Sài Gòn",
    "Ngân hàng Standard Chartered Bank Việt Nam",
    "Ngân hàng Standard Chartered Bank HN",
    "The Shanghai Commercial & Savings Bank CN Đồng Nai",
    "Ngân hàng TMCP Đông Nam Á",
    "Ngân hàng Sài Gòn - Hà Nội",
    "Ngân hàng TNHH MTV Shinhan Việt Nam",
    "Ngân hàng The Siam Commercial Public",
    "Sumitomo Mitsui Banking Corporation HCM",
    "Sumitomo Mitsui Banking Corporation HN",
    "Ngân hàng SinoPac",
    "Ngân hàng Kỹ thương Việt Nam",
    "Taipei Fubon Commercial Bank Ha Noi",
    "Taipei Fubon Commercial Bank TP Ho Chi Minh",
    "United Oversea Bank",
    "Ngân hàng Chính sách xã hội Việt Nam",
    "Ngân hàng Phát triển Việt Nam",
    "Ngân hàng Quốc tế",
    "Ngân hàng VID Public",
    "Ngân hàng Việt Hoa",
    "Ngân hàng Việt Á",
    "Ngân hàng Việt Nam Thương Tín",
    "NHTMCP Bản Việt",
    "Ngân hàng TMCP Ngoại Thương",
    "Ngân hàng công thương Việt Nam",
    "NH TMCP Xây dựng Việt Nam",
    "Ngân hàng Thương mại cổ phần Việt Nam Thịnh Vượng",
    "Ngân hàng Liên doanh Việt Nga",
    "Ngân hàng Vũng Tàu",
    "NH Woori HCM",
    "WOORI BANK Hà Nội",
]
